---
commitizen:
  major_version_zero: true
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.1.0
  version_scheme: semver
  version_files:
    - canisters/name-registry/Cargo.toml:version
    - canisters/operator/Cargo.toml:version
    - canisters/root/Cargo.toml:version
