---
commitizen:
  major_version_zero: true
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.1.0
  version_scheme: semver
  version_files:
    - packages/cns-naming-canister/Cargo.toml:version
    - packages/cns-root-canister/Cargo.toml:version
    - packages/cns-operator-canister/Cargo.toml:version
