[workspace]
members = [
  "packages/cns-naming-canister",
  "packages/cns-root-canister",
  "packages/cns-top-level-domain-canister",
]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
