name: 'Setup Python'
description: Setup Python

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PIP
      run: |
        python -m pip install --upgrade pip
