name: 'Pull request creation'
description: 'Action to create a pull requests'

inputs:
  auto-merge:
    description: 'Wether to set to auto merge the pull request after approval'
    default: false
  pull-request-number:
    description: 'Pull request number to approve'
    required: true
  token:
    description: 'Access token to manage the pull request'
    default: ${{ github.token }}

outputs:
  pull-request-approved:
    description: 'Boolean indicating if the pull request was approved'
    value: ${{ steps.approve-pull-request.outputs.pull-request-approved }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygithub gitpython
      shell: bash
    - name: Approve pull request
      id: approve-pull-request
      run: |
        python .github/actions/pullrequest/approve/main.py
        if [ -f "/tmp/action_outputs.txt" ]; then
          cat "/tmp/action_outputs.txt" >> $GITHUB_OUTPUT
        fi
      shell: bash
      env:
        INPUT_AUTO_MERGE: ${{ inputs.auto-merge }}
        INPUT_PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}
        INPUT_TOKEN: ${{ inputs.token }}
