name: 'Automation'

on:
  push:
    branches:
      - main

jobs:
  update_changelogs:
    name: 'generate-changelogs'
    uses: dfinity/ci-tools/.github/workflows/generate-changelog.yaml@main
    with:
      auto_merge: true
    secrets:
      token: ${{ secrets.GH_PRIVILEGED_TOKEN }}
