name: 'Update changelog'

on: 
  workflow_run:
    workflows: 
      - 'Check commits'
    types:
      - completed
    # branches:
    #   - 'main'

jobs:
  update_changelogs:
    name: 'generate-changelogs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-python
      - name: 'Install Commitzen'
        run: pip install -U commitizen
      - name: 'Update Changelogs'
        run: cz changelog --incremental
      - name: 'Commit and push'
        uses: ./.github/actions/commit-handler
        with: 
          commit-message: 'chore: action updated changelogs'
          skip-if-empty: false
          push-changes: true
