name: 'Update changelog'

on: 
  push:

jobs:
  update_changelogs:
    name: 'generate-changelogs'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-python
      - name: 'Install Commitzen'
        run: pip install -U commitizen
      - name: 'Update Changelogs'
        run: cz changelog --incremental
      - name: 'Commit and push'
        uses: ./.github/actions/commit-handler
        with:
          commit-message: 'chore: auto update changelogs [skip ci]'
          skip-if-empty: true
          push-changes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
