name: 'Update changelog'

on: 
  merge_group:
    types: [checks_requested]
    branches:
      - main

jobs:
  update_changelogs:
    name: 'generate-changelogs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-python
      - name: 'Install Commitzen'
        run: pip install -U commitizen
      - name: 'Update Changelogs'
        run: cz changelog --incremental
      - name: 'Test merge group'
        run: |
          echo 'test merge group'
          exit 1
      # - name: 'Commit and push'
      #   uses: ./.github/actions/commit-handler
      #   with:
      #     commit-message: 'chore: action updated changelogs'
      #     skip-if-empty: false
      #     push-changes: true
