name: Check commits format

on: [pull_request]

jobs:
  check:
    name: conventional-commits:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-python.yaml
      - name: Install Commitzen
        run: pip install -U commitizen
      - name: Check Commit Messages
        run: cz check --rev-range 7ce94d377c947f03a12f7e2db3d80876c0eb0134..HEAD
