name: 'Code style'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled
  merge_group:
    types: [checks_requested]
    branches:
      - main
  push:
    branches:
      - main
      # For external contributions, the suggested flow is as follows:
      #   1. Contributor creates a fork and enables GH Actions on it
      #   2. Contributor develops in a fork, and pushes the changes to a branch named with prefix `dev-gh-`.
      #      The push triggers the tests on the contributor's fork on a Github Runner
      #   3. Once the code in a branch is ready and passes the tests, the contributor creates a PR on the main repo.
      - 'dev-gh-*'

env:
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .

jobs:
  rust:
    name: 'consistent-style:required'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Format code'
        run: cargo fmt --all -- --check
        env:
          RUST_BACKTRACE: 1
      - name: 'Lint code'
        run: cargo clippy --verbose --tests --benches --workspace -- -D clippy::all
        env:
          RUST_BACKTRACE: 1

  motoko_code_style:
    name: 'motoko-code-style:required'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main

      - name: 'Check code formatting'
        run: pnpm format:check
