name: code_style

on:
  merge_group:
  pull_request:

jobs:
  rust_code_style:
    name: rust_code_style:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Lint code
        run: cargo clippy --all-targets --all-features

  motoko_code_style:
    name: motoko_code_style:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main

      - name: Check code formatting
        run: pnpm format:check
