name: 'Code style'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled
  merge_group:
    types: [checks_requested]
    branches:
      - main

jobs:
  rust_code_style:
    name: 'rust-code-style:required'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Check code formatting'
        run: cargo fmt --all -- --check

      - name: 'Lint code'
        run: cargo clippy --all-targets --all-features

  motoko_code_style:
    name: 'motoko-code-style:required'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main

      - name: 'Check code formatting'
        run: pnpm format:check
