name: 'Code tests'

on: 
  pull_request:
  push:
    branches:
      - main

env:
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .

jobs:
  rust_test:
    name: 'rust-tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust
      - name: 'Test cargo crates'
        run: cargo test
